//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NW.NGramTextClassification.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NW.NGramTextClassification.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Label&quot;: &quot;en&quot;,
        ///    &quot;Text&quot;: &quot;We are looking for several skilled and driven developers to join our team.&quot;
        ///  },
        ///  {
        ///    &quot;Label&quot;: &quot;sv&quot;,
        ///    &quot;Text&quot;: &quot;Vår kund erbjuder trivsel, arbetsglädje och en trygg arbetsmiljö.&quot;
        ///  }
        ///].
        /// </summary>
        public static string ShortLabeledExamplesAsJson {
            get {
                return ResourceManager.GetString("ShortLabeledExamplesAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;MinimumAccuracySingleLabel&quot;: 0.5,
        ///  &quot;MinimumAccuracyMultipleLabels&quot;: 0,
        ///  &quot;Results&quot;: [
        ///    {
        ///      &quot;TextSnippet&quot;: {
        ///        &quot;Text&quot;: &quot;VerksamhetsbeskrivningGoGift is a company which focuses on innovative gifts and gift cards solutions. GoGift has activities in every Nordic country and addresses both private as well as corporate customers. GoGift distributes gift cards for thousands of shops, brands and experiences delivered with post, email or SMS. The Super Gift Card, one of the most popular gift [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextClassifierrSessionCLE00AsJson {
            get {
                return ResourceManager.GetString("TextClassifierrSessionCLE00AsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;MinimumAccuracySingleLabel&quot;: 0.5,
        ///    &quot;MinimumAccuracyMultipleLabels&quot;: 0,
        ///    &quot;Results&quot;: [
        ///      {
        ///        &quot;TextSnippet&quot;: {
        ///          &quot;Text&quot;: &quot;VerksamhetsbeskrivningGoGift is a company which focuses on innovative gifts and gift cards solutions. GoGift has activities in every Nordic country and addresses both private as well as corporate customers. GoGift distributes gift cards for thousands of shops, brands and experiences delivered with post, email or SMS. The Super Gift Card, one of the most  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextClassifierrSessionCLE00DisabledAsJson {
            get {
                return ResourceManager.GetString("TextClassifierrSessionCLE00DisabledAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Text&quot;: &quot;We are looking for several skilled and driven developers to join our team.&quot;
        ///}.
        /// </summary>
        public static string TextSnippetAsJson {
            get {
                return ResourceManager.GetString("TextSnippetAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Text&quot;: &quot;We are looking for several skilled and driven developers to join our team.&quot;
        ///  },
        ///  {
        ///    &quot;Text&quot;: &quot;Vår kund erbjuder trivsel, arbetsglädje och en trygg arbetsmiljö.&quot;
        ///  }
        ///].
        /// </summary>
        public static string TextSnippetsAsJson {
            get {
                return ResourceManager.GetString("TextSnippetsAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;DoForMonogram&quot;: true,
        ///    &quot;DoForBigram&quot;: true,
        ///    &quot;DoForTrigram&quot;: true,
        ///    &quot;DoForFourgram&quot;: true,
        ///    &quot;DoForFivegram&quot;: true
        ///}.
        /// </summary>
        public static string TokenizerRuleSetAsJson {
            get {
                return ResourceManager.GetString("TokenizerRuleSetAsJson", resourceCulture);
            }
        }
    }
}
