name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install dotnet SDK 8.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Display installed SDKs
      run:  dotnet --info
      
    - name: Restore dependencies
      run: dotnet restore -s https://api.nuget.org/v3/index.json --verbosity n
      
    - name: Build
      working-directory: ./
      run: dotnet build --no-restore
      
    - name: Run unit tests
      working-directory: ./
      run: dotnet test --no-build --verbosity normal
      
    - name: Find packages
      run: Get-ChildItem -Recurse -Filter *.nupkg | Select-Object FullName

    - name: Pack library
      working-directory: ./src/NW.NGramTextClassification
      run: dotnet pack --configuration Release --no-build --output bin/Release

    - name: Publish library to NuGet.org
      run: Get-ChildItem ./src/NW.NGramTextClassification/bin/Release/*.nupkg | ForEach-Object { dotnet nuget push $_.FullName --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate }

    - name: Pack tool
      working-directory: ./src/NW.NGramTextClassification.CLI
      run: dotnet pack --configuration Release --no-build

    - name: Publish tool to NuGet.org
      run: Get-ChildItem ./src/NW.NGramTextClassification.CLI/nupkg/*.nupkg | ForEach-Object { dotnet nuget push $_.FullName --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate }